### ISSUE TITLE
Example workflow not working 

### ISSUE THREAD

**Issue by DrMattG** [gls21/Dynameta#1]
I am trying to run the example workflow with the sample data. I can not get it to run. First the number of papers is not showing ![image](https://user-images.githubusercontent.com/11541781/221369343-e505fe5e-6086-470d-9baa-a95209005f3d.png) and when I try to run the model I get an error message "There is currently insufficient data for this model to run, please select an additional or alternative biodiversity metric category."
![image](https://user-images.githubusercontent.com/11541781/221369422-8a6e23fc-0de6-456c-8c74-d13102faee6f.png)

**Comment by gls21** [comment]
Hi Matt, thanks for pointing this out!

I haven't come across this issue so far through testing on my computer, though was able to replicate these issues with someone else's computer today. It's due to the reading of the sample data csv file so that the column name of the 1st column is being preceded by i.., which causes issues downstream. 

We have fixed this by getting the app to read in an rds version of the sample data, so the example workflow should now work for you if you re-install the package. Please report any further issues if you come across them. 

And just to let you know, we are finding a similar issue for if you choose to upload your own data (rather than use the sample data) which we are currently in the process of fixing. Thanks again.

**Comment by DrMattG** [comment]
Thank you for the fix! That works for me now.

**Comment by gls21** [comment]
Hi again,

Just to update you that we have now fixed the issue for uploading your own data, equivalent to the one found you for the sample data. 

After some more investigation, we found that the reason yours wasn’t reading the sample data correctly, whereas mine was, is due to a difference in the locale settings, which can be found in sessionInfo(). The locale we’ve identified which causes this issue is English_United Kingdom.1252, whereas mine is set to English_United Kingdom.utf8. 

We did not implement the same fix as we did for the sample data as we did not wish for users to have to convert their csv to a rds file before uploading data to the Dynameta app.

Instead, in this case, we have switched from using the base R function read.csv() to the readr function read_csv(), which is more robust to issues like this. The default behaviour for read_csv() is to assume UTF-8 encoding of your input, whereas read.csv() uses the native encoding of your system to load the CSV. We have also added a check to make sure the file that the user is uploading has either UTF-8 or ASCII encoding as these both work with read_csv, whereas a file with ANSI encoding still leads to errors.
